services:
  # lara_backend:
  #   build:
  #     context: .
  #   env_file:
  #     - ../.env
  #   environment:
  #     # Override for container-to-container communication
  #     - DDB_ENDPOINT=http://dynamodb-local:8000
  #     - S3_ENDPOINT=http://minio:9000
  #   volumes:
  #     - ..:/app
  #   working_dir: /app
  #   command: sleep infinity
  #   stop_grace_period: 2s
  #   depends_on: # Ensures services start before the app container
  #     - dynamodb-local
  #     - minio

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  # minio:
  #   image: minio/minio:latest
  #   container_name: minio
  #   command: server /data --console-address ":9001"
  #   env_file:
  #     - ../.env
  #   ports:
  #     - "9000:9000" # API
  #     - "9001:9001" # Console
  #   environment:
  #     MINIO_ROOT_USER: ${S3_ACCESS_KEY}
  #     MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
  #   volumes:
  #     - "./minio_data:/data"
